import Main from "@/components/main";
import { type GetServerSidePropsContext, type NextPage } from "next";
import Head from "next/head";
import { makeDynamicContainer } from "@/utils/makeDynamicContainer";
import { lazy } from "react";

const DynamicTheOtherSide = lazy(() =>
    // eslint-disable-next-line @typescript-eslint/no-unsafe-return
    makeDynamicContainer({
        global: "remote",
        url: "http://localhost:3001",
        componentName: "./Div",
    })
);

export const getServerSideProps = async (
    context: GetServerSidePropsContext
) => {
    const page: any = DynamicTheOtherSide;

    // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
    if (page.getServerSideProps) {
        // eslint-disable-next-line @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call
        return page.getServerSideProps(context);
    }

    return {
        props: {},
    };
};

const Home: NextPage = () => {
    console.log(DynamicTheOtherSide);
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Main>
                <DynamicTheOtherSide />
            </Main>
        </>
    );
};

export default Home;
